//! `blacksilk-daa-sim`: runs every scenario for every candidate difficulty rule and
//! prints (or writes) the Markdown report.
//!
//! ```text
//! blacksilk-daa-sim [--selection [--only <a~b>] | --redteam] [--quick] [--seed <u64>] [--threads <n>] [--race-trials <n>] [--out <file>]
//! ```

#![forbid(unsafe_code)]

use blacksilk_daa_sim::report::{render, run, Config};
use blacksilk_daa_sim::rules::candidates;
use std::process::ExitCode;
use std::time::Instant;

const USAGE: &str =
    "usage: blacksilk-daa-sim [--selection [--only <a~b>] | --redteam] [--quick] [--seed <u64>] [--threads <n>] [--race-trials <n>] [--out <file>]";

/// The default base seed of the published results.
const DEFAULT_SEED: u64 = 0x0B1A_C051_1C03;

fn parse<T: std::str::FromStr>(v: Option<&String>, flag: &str) -> Result<T, String> {
    let v = v.ok_or(format!("{flag} needs a value"))?;
    let v = v.strip_prefix("0x").map_or_else(
        || v.parse::<T>().map_err(|_| ()),
        |hex| {
            u64::from_str_radix(hex, 16)
                .map_err(|_| ())
                .and_then(|x| x.to_string().parse::<T>().map_err(|_| ()))
        },
    );
    v.map_err(|_| format!("bad value for {flag}"))
}

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let mut quick = false;
    let mut selection = false;
    let mut redteam = false;
    let mut only: Option<String> = None;
    let mut seed = DEFAULT_SEED;
    let mut threads = std::thread::available_parallelism().map_or(1, |n| n.get().min(4));
    let mut race_trials = None;
    let mut out = None;
    let mut i = 0;
    while i < args.len() {
        let r: Result<(), String> = match args[i].as_str() {
            "--only" => {
                i += 1;
                args.get(i)
                    .cloned()
                    .map(|v| only = Some(v))
                    .ok_or("--only needs a value".into())
            }
            "--redteam" => {
                redteam = true;
                Ok(())
            }
            "--selection" => {
                selection = true;
                Ok(())
            }
            "--quick" => {
                quick = true;
                Ok(())
            }
            "--seed" => {
                i += 1;
                parse(args.get(i), "--seed").map(|v| seed = v)
            }
            "--threads" => {
                i += 1;
                parse(args.get(i), "--threads").map(|v| threads = v)
            }
            "--race-trials" => {
                i += 1;
                parse(args.get(i), "--race-trials").map(|v| race_trials = Some(v))
            }
            "--out" => {
                i += 1;
                args.get(i)
                    .cloned()
                    .map(|v| out = Some(v))
                    .ok_or("--out needs a value".into())
            }
            _ => Err(format!("unknown argument {}", args[i])),
        };
        if let Err(e) = r {
            eprintln!("{e}\n{USAGE}");
            return ExitCode::from(2);
        }
        i += 1;
    }
    if redteam {
        return run_redteam(quick, seed, threads, out);
    }
    if selection {
        return run_selection(quick, seed, threads, out, only);
    }
    let mut cfg = if quick {
        Config::quick(seed, threads)
    } else {
        Config::full(seed, threads)
    };
    if let Some(n) = race_trials {
        cfg.race_trials = n;
    }
    let rules = candidates();
    let started = Instant::now();
    let results = run(&cfg, &rules);
    let header = format!(
        "# Difficulty-rule simulation results\n\n\
         Generated by `cargo run --release -p blacksilk-daa-sim --{}{}{}` \
         ({} mode, {:.0} s on {} threads). Rules: {}.\n",
        if quick { " --quick" } else { "" },
        if seed == DEFAULT_SEED {
            String::new()
        } else {
            format!(" --seed {seed:#x}")
        },
        race_trials.map_or(String::new(), |n| format!(" --race-trials {n}")),
        if quick { "quick" } else { "full" },
        started.elapsed().as_secs_f64(),
        threads,
        rules
            .iter()
            .map(|r| r.name())
            .collect::<Vec<_>>()
            .join("; ")
    );
    let md = render(&cfg, &results, &header);
    match out {
        Some(path) => {
            if let Err(e) = std::fs::write(&path, &md) {
                eprintln!("cannot write {path}: {e}");
                return ExitCode::FAILURE;
            }
            println!("{md}");
        }
        None => println!("{md}"),
    }
    ExitCode::SUCCESS
}

/// The default base seed of the W0-03b selection study.
const SELECTION_SEED: u64 = 0x5E1E_C7ED;

fn run_selection(
    quick: bool,
    seed: u64,
    threads: usize,
    out: Option<String>,
    only: Option<String>,
) -> ExitCode {
    use blacksilk_daa_sim::family::selection_candidates;
    use blacksilk_daa_sim::selection::{render, run, SelConfig};
    let seed = if seed == DEFAULT_SEED {
        SELECTION_SEED
    } else {
        seed
    };
    let cfg = if quick {
        SelConfig::quick(seed, threads)
    } else {
        SelConfig::full(seed, threads)
    };
    // `--only a~b~c`: keep the candidates whose name contains any of the substrings.
    let rules: Vec<_> = selection_candidates()
        .into_iter()
        .filter(|r| {
            only.as_ref()
                .is_none_or(|o| o.split('~').any(|s| r.name().contains(s)))
        })
        .collect();
    let started = Instant::now();
    let res = run(&cfg, &rules);
    let header = format!(
        "# Difficulty-rule selection study (generated)\n\n\
         Generated by `cargo run --release -p blacksilk-daa-sim -- --selection{}{}{}` \
         ({} mode, {:.0} s on {} threads).\n",
        if quick { " --quick" } else { "" },
        if seed == SELECTION_SEED {
            String::new()
        } else {
            format!(" --seed {seed:#x}")
        },
        only.as_ref()
            .map_or(String::new(), |o| format!(" --only '{o}'")),
        if quick { "quick" } else { "full" },
        started.elapsed().as_secs_f64(),
        threads
    );
    let md = render(&cfg, &res, &header);
    if let Some(path) = out {
        if let Err(e) = std::fs::write(&path, &md) {
            eprintln!("cannot write {path}: {e}");
            return ExitCode::FAILURE;
        }
    }
    println!("{md}");
    ExitCode::SUCCESS
}

/// The default base seed of the RT-DAA red-team study.
const REDTEAM_SEED: u64 = 0x0DAA_7EA3;

fn run_redteam(quick: bool, seed: u64, threads: usize, out: Option<String>) -> ExitCode {
    use blacksilk_daa_sim::redteam::{render, run_subject, RtConfig, Subject};
    let seed = if seed == DEFAULT_SEED {
        REDTEAM_SEED
    } else {
        seed
    };
    let cfg = if quick {
        RtConfig::quick(seed, threads)
    } else {
        RtConfig::full(seed, threads)
    };
    let started = Instant::now();
    let res: Vec<_> = [
        Subject::recommended(),
        Subject::anchored(
            "Candidate fix: LWMA-75 step T/2, clock warmed over 11 blocks",
            11,
        ),
        Subject::current(),
    ]
    .iter()
    .map(|s| {
        run_subject(&cfg, s, &|m| {
            eprintln!(
                "[{:>6.0} s] {}: {m}",
                started.elapsed().as_secs_f64(),
                s.name
            )
        })
    })
    .collect();
    let header = format!(
        "# Red-team study of the recommended difficulty rule (generated)\n\n\
         Generated by `cargo run --release -p blacksilk-daa-sim -- --redteam{}{}` \
         ({} mode, {:.0} s on {} threads).\n",
        if quick { " --quick" } else { "" },
        if seed == REDTEAM_SEED {
            String::new()
        } else {
            format!(" --seed {seed:#x}")
        },
        if quick { "quick" } else { "full" },
        started.elapsed().as_secs_f64(),
        threads
    );
    let mut md = render(&cfg, &res, &header);
    // The selection study's criteria, on its own seed, for the rule under attack (its
    // row must reproduce selection.md) and for the candidate fix.
    {
        use blacksilk_daa_sim::family::recommended;
        use blacksilk_daa_sim::redteam::Anchored;
        use blacksilk_daa_sim::selection::{self, SelConfig};
        use blacksilk_daa_sim::DifficultyRule;
        eprintln!(
            "[{:>6.0} s] selection criteria",
            started.elapsed().as_secs_f64()
        );
        let scfg = if quick {
            SelConfig::quick(SELECTION_SEED, threads)
        } else {
            SelConfig::full(SELECTION_SEED, threads)
        };
        let rules: Vec<Box<dyn DifficultyRule>> = vec![
            Box::new(recommended()),
            Box::new(Anchored {
                window: 75,
                warm: 11,
            }),
        ];
        let sres = selection::run(&scfg, &rules);
        md.push_str(&selection::render(
            &scfg,
            &sres,
            "\n# Selection criteria: rule under attack and candidate fix (generated)\n\n\
             The selection study's runner (`selection::run`) on its main seed `0x5e1ec7ed`, for the two rules only.\n",
        ));
    }
    if let Some(path) = out {
        if let Err(e) = std::fs::write(&path, &md) {
            eprintln!("cannot write {path}: {e}");
            return ExitCode::FAILURE;
        }
    }
    println!("{md}");
    ExitCode::SUCCESS
}
