//! `blacksilk-daa-sim`: runs every scenario for every candidate difficulty rule and
//! prints (or writes) the Markdown report.
//!
//! ```text
//! blacksilk-daa-sim [--quick] [--seed <u64>] [--threads <n>] [--race-trials <n>] [--out <file>]
//! ```

#![forbid(unsafe_code)]

use blacksilk_daa_sim::report::{render, run, Config};
use blacksilk_daa_sim::rules::candidates;
use std::process::ExitCode;
use std::time::Instant;

const USAGE: &str =
    "usage: blacksilk-daa-sim [--quick] [--seed <u64>] [--threads <n>] [--race-trials <n>] [--out <file>]";

/// The default base seed of the published results.
const DEFAULT_SEED: u64 = 0x0B1A_C051_1C03;

fn parse<T: std::str::FromStr>(v: Option<&String>, flag: &str) -> Result<T, String> {
    let v = v.ok_or(format!("{flag} needs a value"))?;
    let v = v.strip_prefix("0x").map_or_else(
        || v.parse::<T>().map_err(|_| ()),
        |hex| {
            u64::from_str_radix(hex, 16)
                .map_err(|_| ())
                .and_then(|x| x.to_string().parse::<T>().map_err(|_| ()))
        },
    );
    v.map_err(|_| format!("bad value for {flag}"))
}

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let mut quick = false;
    let mut seed = DEFAULT_SEED;
    let mut threads = std::thread::available_parallelism().map_or(1, |n| n.get().min(4));
    let mut race_trials = None;
    let mut out = None;
    let mut i = 0;
    while i < args.len() {
        let r: Result<(), String> = match args[i].as_str() {
            "--quick" => {
                quick = true;
                Ok(())
            }
            "--seed" => {
                i += 1;
                parse(args.get(i), "--seed").map(|v| seed = v)
            }
            "--threads" => {
                i += 1;
                parse(args.get(i), "--threads").map(|v| threads = v)
            }
            "--race-trials" => {
                i += 1;
                parse(args.get(i), "--race-trials").map(|v| race_trials = Some(v))
            }
            "--out" => {
                i += 1;
                args.get(i)
                    .cloned()
                    .map(|v| out = Some(v))
                    .ok_or("--out needs a value".into())
            }
            _ => Err(format!("unknown argument {}", args[i])),
        };
        if let Err(e) = r {
            eprintln!("{e}\n{USAGE}");
            return ExitCode::from(2);
        }
        i += 1;
    }
    let mut cfg = if quick {
        Config::quick(seed, threads)
    } else {
        Config::full(seed, threads)
    };
    if let Some(n) = race_trials {
        cfg.race_trials = n;
    }
    let rules = candidates();
    let started = Instant::now();
    let results = run(&cfg, &rules);
    let header = format!(
        "# Difficulty-rule simulation results\n\n\
         Generated by `cargo run --release -p blacksilk-daa-sim --{}{}{}` \
         ({} mode, {:.0} s on {} threads). Rules: {}.\n",
        if quick { " --quick" } else { "" },
        if seed == DEFAULT_SEED {
            String::new()
        } else {
            format!(" --seed {seed:#x}")
        },
        race_trials.map_or(String::new(), |n| format!(" --race-trials {n}")),
        if quick { "quick" } else { "full" },
        started.elapsed().as_secs_f64(),
        threads,
        rules
            .iter()
            .map(|r| r.name())
            .collect::<Vec<_>>()
            .join("; ")
    );
    let md = render(&cfg, &results, &header);
    match out {
        Some(path) => {
            if let Err(e) = std::fs::write(&path, &md) {
                eprintln!("cannot write {path}: {e}");
                return ExitCode::FAILURE;
            }
            println!("{md}");
        }
        None => println!("{md}"),
    }
    ExitCode::SUCCESS
}
