[package]
name = "primitives"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2 = "0.10"
ed25519-dalek = "2.1"
curve25519-dalek = "4.1"
rand = "0.8"
rand_core = "=0.6.4"
serde = { version = "1.0", features = ["derive"] }
