//! The v3 difficulty rule (docs/consensus.md §4): LWMA-1, N = 75, counted clock
//! step `max(1, T/2)`, the clock warmed over the 11 blocks before the window.
//!
//! The expected values here and in `tests/data/lwma_vectors.txt` come from
//! `tools/vectors/lwma_warm.py`, written from the spec text, not from this crate.

use blacksilk_consensus::difficulty::next_difficulty;

const T: u64 = 120;
const N: usize = 75;

/// An on-target history: `blocks` blocks 120 s apart at difficulty `d`.
fn steady(blocks: usize, d: u64) -> (Vec<u64>, Vec<u128>) {
    let ts = (0..blocks as u64).map(|i| 1_000_000 + i * T).collect();
    let cd = (0..blocks as u128).map(|i| (i + 1) * d as u128).collect();
    (ts, cd)
}

/// The red-team golden case (docs/evidence/daa-sim-2026-09-27/redteam.md, RT-1):
/// 87 on-target blocks at D = 10^6 whose window-oldest stamp (index 11 of 87) is
/// 1 300 s low. Without the warm-up the counted clock restarts at that low stamp
/// and counts the first solve time as 720 s (6T cap): 998 248. With the warm-up the
/// anchor is `ts[10] + T/2`, the first solve time counts 180 s: 999 824. The v3
/// rule has the warm-up, so 999 824 applies.
///
/// This stamp sequence is a function vector: in a steady chain the MTP rule would
/// refuse a stamp that low (the lowest valid one is `ts[5] + 1`). An attacker gets
/// the same lag with forward stamps before it (the redteam's rollout controller).
#[test]
fn window_start_lag_golden_case() {
    let (mut ts, cd) = steady(87, 1_000_000);
    assert_eq!(next_difficulty(&ts, &cd, T, N, 1), 1_000_000);
    ts[11] -= 1_300;
    assert_eq!(next_difficulty(&ts, &cd, T, N, 1), 999_824);
    // Only the 76 window stamps: no warm-up possible, the old anchor applies.
    assert_eq!(next_difficulty(&ts[11..], &cd[11..], T, N, 1), 998_248);
}

/// Every vector of `tests/data/lwma_vectors.txt` (generated by
/// `tools/vectors/lwma_warm.py` from the spec text): steady state, 2x/10x steps,
/// genesis-near short windows, 1-second blocks, the genesis gap, warm-up edge
/// cases, the 6T cap, u128 extremes and random adversarial histories.
#[test]
fn independent_vectors() {
    let text = include_str!("data/lwma_vectors.txt");
    let mut count = 0;
    for line in text
        .lines()
        .filter(|l| !l.starts_with('#') && !l.is_empty())
    {
        let f: Vec<&str> = line.split(' ').collect();
        assert_eq!(f.len(), 8, "{line}");
        let int = |s: &str| s.parse::<u64>().unwrap_or_else(|_| panic!("{line}"));
        let (name, t, n, d0) = (f[0], int(f[1]), int(f[2]) as usize, int(f[3]));
        let mut ts = vec![int(f[4])];
        if f[5] != "-" {
            for dt in f[5].split(',') {
                let dt: i128 = dt.parse().unwrap_or_else(|_| panic!("{line}"));
                ts.push((*ts.last().unwrap() as i128 + dt) as u64);
            }
        }
        let mut cd: Vec<u128> = Vec::with_capacity(ts.len());
        for d in f[6].split(',') {
            cd.push(cd.last().copied().unwrap_or(0) + int(d) as u128);
        }
        assert_eq!(ts.len(), cd.len(), "{name}");
        assert_eq!(next_difficulty(&ts, &cd, t, n, d0), int(f[7]), "{name}");
        count += 1;
    }
    assert!(count >= 100, "{count} vectors");
}
