#!/usr/bin/env bash
# `unsafe` inventory of the shipped dependency graph (W3-44, dossier 44 §2.4):
# a reviewable report, not a gate. BlackSilk's own crates forbid unsafe code
# (the `lint` CI job checks every crate root); "pure Rust" means no foreign
# code, and std-level dependencies (tokio, getrandom, the SIMD backends) do
# contain `unsafe`. This lists every crates.io crate in the release graph with
# the number of source lines that use the keyword, so a new crate or a jump
# in a count is visible in review.
#
# Graph: the main workspace, normal and build edges (no dev), resolved for
# each release target (deny.toml [graph] targets), merged. Count: lines of
# `.rs` files outside the crate's tests/, benches/ and examples/ that contain
# the word `unsafe` and are not `//` comments (a line count, not an audit:
# an `unsafe fn` declaration, an `unsafe` block and a comment inside a block
# each count as one line or not at all).
#
# Usage: unsafe-report.sh           write docs/reviews/unsafe-inventory.md
#        unsafe-report.sh --check   exit 1 if the committed file is stale
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"
export LC_ALL=C

out=docs/reviews/unsafe-inventory.md
targets=(
  x86_64-unknown-linux-gnu
  aarch64-unknown-linux-gnu
  x86_64-pc-windows-msvc
  aarch64-apple-darwin
)
cargo_home="${CARGO_HOME:-$HOME/.cargo}"
if ! cargo fetch --locked --offline >/dev/null 2>&1; then
  cargo fetch --locked >/dev/null
fi

# "name version kind" for every registry package of every target graph; kind
# is "proc-macro" (runs in the compiler only) or "lib".
graph() {
  local t
  for t in "${targets[@]}"; do
    cargo tree --locked --offline --workspace -e normal,build --target "$t" \
      --prefix none --format '{p}' | tr -d '\r' | awk '
        NF < 2 { next }
        # Path (workspace) crates carry their directory in parentheses.
        $3 ~ /^\(/ && $3 != "(proc-macro)" && $3 != "(*)" { next }
        { k = "lib"; for (i = 3; i <= NF; i++) if ($i == "(proc-macro)") k = "proc-macro"
          sub(/^v/, "", $2); print $1, $2, k }'
  done | sort -u
}

src_dir() {
  local d
  for d in "$cargo_home"/registry/src/*/"$1-$2"; do
    [ -d "$d" ] && { printf '%s\n' "$d"; return 0; }
  done
  return 1
}

# Lines using `unsafe` in a crate directory (see the header for the rule).
count_unsafe() {
  find "$1" -type f -name '*.rs' \
    -not -path "$1/tests/*" -not -path "$1/benches/*" -not -path "$1/examples/*" \
    -exec grep -hE '(^|[^A-Za-z0-9_])unsafe([^A-Za-z0-9_]|$)' {} + 2>/dev/null |
    grep -cvE '^[[:space:]]*//' || true
}

# The crate root's own lint, if it has one.
root_lint() {
  local lib="$1/src/lib.rs"
  [ -f "$lib" ] || { echo "-"; return; }
  if grep -qE '^[[:space:]]*#!\[forbid\((.*[, ])?unsafe_code' "$lib"; then
    echo "forbid"
  elif grep -qE '^[[:space:]]*#!\[deny\((.*[, ])?unsafe_code' "$lib"; then
    echo "deny"
  else
    echo "-"
  fi
}

generate() {
  local rows zero total=0 with=0 name ver kind dir n lint
  rows="$(mktemp)"
  zero="$(mktemp)"
  while read -r name ver kind; do
    [ -n "$name" ] || continue
    dir="$(src_dir "$name" "$ver")" || { echo "unsafe-report: no source for $name $ver" >&2; exit 2; }
    total=$((total + 1))
    n="$(count_unsafe "$dir")"
    lint="$(root_lint "$dir")"
    if [ "$n" -gt 0 ]; then
      with=$((with + 1))
      printf '%s\t%s\t%s\t%s\t%s\n' "$n" "$name" "$ver" "$kind" "$lint" >> "$rows"
    else
      printf '%s %s\n' "$name" "$ver" >> "$zero"
    fi
  done < <(graph)

  cat <<EOF
# \`unsafe\` inventory of the release dependency graph

Generated by \`bash .github/scripts/unsafe-report.sh\`; do not edit by hand. CI
(job \`deny\`) warns when this file no longer matches \`Cargo.lock\`.

**What this is.** Every crates.io crate that the shipped binaries' graph
contains (main workspace, normal and build edges, resolved for each release
target in \`deny.toml\`), with the number of source lines that use the
\`unsafe\` keyword (the rule is in the script header). It is a review aid, not
a gate and not an assessment: a count says where \`unsafe\` is, not whether it
is correct. None of these crates has been reviewed line by line by the
project; docs/reviews/dependency-review.md records what was read.

**BlackSilk's own crates** declare \`#![forbid(unsafe_code)]\` at every crate
root (CI job \`lint\`); the only \`unsafe\` in the repository outside
\`third_party/\` is the zkVM guest SDK's \`ecall\`, which runs inside the VM,
not in a shipped binary. \`third_party/\` holds three patched Plonky3 crates
that keep upstream's \`unsafe\` unchanged; they are path crates and so not
listed below (their registry originals \`p3-dft\`, \`p3-fri\`,
\`p3-merkle-tree\` 0.7.0 are the reviewed baseline, third_party/README.md).

**Graph:** $total crates.io crates; $with contain \`unsafe\`, $((total - with)) do not.
\`proc-macro\` crates run inside the compiler at build time only; \`lib\`
crates are linked into the binaries. "Root lint" is the crate's own
\`unsafe_code\` lint in \`src/lib.rs\`, if any.

| Lines with \`unsafe\` | Crate | Version | Kind | Root lint |
|---:|---|---|---|---|
EOF
  sort -t$'\t' -k1,1nr -k2,2 "$rows" | awk -F'\t' '{ printf "| %s | %s | %s | %s | %s |\n", $1, $2, $3, $4, $5 }'
  cat <<EOF

**Without \`unsafe\`** ($((total - with))): $(sort "$zero" | awk '{ printf "%s%s %s", (NR > 1 ? ", " : ""), $1, $2 }').
EOF
  rm -f "$rows" "$zero"
}

if [ "${1:-}" = --check ]; then
  tmp="$(mktemp)"
  generate > "$tmp"
  if diff -q <(tr -d '\r' < "$out") "$tmp" >/dev/null 2>&1; then
    echo "unsafe-report: $out is current"
    rm -f "$tmp"
    exit 0
  fi
  diff <(tr -d '\r' < "$out" 2>/dev/null) "$tmp" | head -n 40 || true
  rm -f "$tmp"
  echo "unsafe-report: $out is stale; run bash .github/scripts/unsafe-report.sh and commit it"
  exit 1
fi
generate > "$out"
echo "unsafe-report: wrote $out"
