[workspace]
members = [
    "node",
    "wallet",
    "primitives",
    "miner"
]

[package]
name = "BlackSilk"
version = "0.1.0"
edition = "2024"

[dependencies]
node = { path = "node" }
primitives = { path = "primitives" }
