global:
  smtp_smarthost: '${SMTP_HOST:-localhost:587}'
  smtp_from: '${SMTP_FROM:-alerts@blacksilk.network}'
  smtp_auth_username: '${SMTP_USERNAME:-""}'
  smtp_auth_password: '${SMTP_PASSWORD:-""}'

route:
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'default'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 10s
      repeat_interval: 1h
    
    - match:
        component: security
      receiver: 'security-alerts'
      group_wait: 5s
      repeat_interval: 30m
    
    - match:
        component: marketplace
      receiver: 'marketplace-alerts'
    
    - match:
        severity: warning
      receiver: 'warning-alerts'

receivers:
  - name: 'default'
    email_configs:
      - to: '${ALERT_EMAIL_DEFAULT:-admin@blacksilk.network}'
        subject: '[BlackSilk] {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Component: {{ .Labels.component }}
          Instance: {{ .Labels.instance }}
          {{ end }}

  - name: 'critical-alerts'
    email_configs:
      - to: '${ALERT_EMAIL_CRITICAL:-ops@blacksilk.network}'
        subject: '🚨 [CRITICAL] BlackSilk Alert: {{ .GroupLabels.alertname }}'
        body: |
          CRITICAL ALERT TRIGGERED
          
          {{ range .Alerts }}
          🔴 Alert: {{ .Annotations.summary }}
          📝 Description: {{ .Annotations.description }}
          ⚠️ Severity: {{ .Labels.severity }}
          🔧 Component: {{ .Labels.component }}
          🖥️ Instance: {{ .Labels.instance }}
          ⏰ Started: {{ .StartsAt }}
          {{ if .EndsAt }}⏹️ Ended: {{ .EndsAt }}{{ end }}
          
          🔗 Silence: {{ .SilenceURL }}
          {{ end }}
    
    # Uncomment to enable Slack notifications
    # slack_configs:
    #   - api_url: '${SLACK_WEBHOOK_URL}'
    #     channel: '#blacksilk-alerts'
    #     title: '🚨 Critical BlackSilk Alert'
    #     text: |
    #       {{ range .Alerts }}
    #       *{{ .Annotations.summary }}*
    #       {{ .Annotations.description }}
    #       Severity: {{ .Labels.severity }}
    #       {{ end }}

  - name: 'security-alerts'
    email_configs:
      - to: '${ALERT_EMAIL_SECURITY:-security@blacksilk.network}'
        subject: '🛡️ [SECURITY] BlackSilk Security Alert: {{ .GroupLabels.alertname }}'
        body: |
          SECURITY ALERT - IMMEDIATE ATTENTION REQUIRED
          
          {{ range .Alerts }}
          🛡️ Alert: {{ .Annotations.summary }}
          📝 Description: {{ .Annotations.description }}
          ⚠️ Severity: {{ .Labels.severity }}
          🔧 Component: {{ .Labels.component }}
          🖥️ Instance: {{ .Labels.instance }}
          ⏰ Started: {{ .StartsAt }}
          
          This is a security-related alert that requires immediate investigation.
          {{ end }}

  - name: 'marketplace-alerts'
    email_configs:
      - to: '${ALERT_EMAIL_MARKETPLACE:-marketplace@blacksilk.network}'
        subject: '[Marketplace] BlackSilk Alert: {{ .GroupLabels.alertname }}'
        body: |
          MARKETPLACE ALERT
          
          {{ range .Alerts }}
          🛍️ Alert: {{ .Annotations.summary }}
          📝 Description: {{ .Annotations.description }}
          ⚠️ Severity: {{ .Labels.severity }}
          🖥️ Instance: {{ .Labels.instance }}
          ⏰ Started: {{ .StartsAt }}
          {{ end }}

  - name: 'warning-alerts'
    email_configs:
      - to: '${ALERT_EMAIL_WARNING:-monitoring@blacksilk.network}'
        subject: '[Warning] BlackSilk Alert: {{ .GroupLabels.alertname }}'
        body: |
          WARNING ALERT
          
          {{ range .Alerts }}
          ⚠️ Alert: {{ .Annotations.summary }}
          📝 Description: {{ .Annotations.description }}
          🔧 Component: {{ .Labels.component }}
          🖥️ Instance: {{ .Labels.instance }}
          ⏰ Started: {{ .StartsAt }}
          {{ end }}

# Inhibit rules to prevent spam
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']

templates:
  - '/etc/alertmanager/templates/*.tmpl'
