# BlackSilk Blockchain - Prometheus Configuration
# This file configures Prometheus monitoring for BlackSilk network infrastructure

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    network: "${BLACKSILK_NETWORK:-testnet}"
    cluster: "blacksilk-${BLACKSILK_NETWORK:-testnet}"

rule_files:
  - "rules/*.yml"

scrape_configs:
  # BlackSilk Node Metrics
  - job_name: 'blacksilk-node'
    static_configs:
      - targets: 
          - 'localhost:9333'  # Testnet HTTP API
          - 'localhost:19333' # Mainnet HTTP API (when available)
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 8s
    params:
      format: ['prometheus']
    basic_auth:
      username: '${PROMETHEUS_USERNAME:-admin}'
      password: '${PROMETHEUS_PASSWORD:-changeme}'

  # BlackSilk Miner Metrics
  - job_name: 'blacksilk-miner'
    static_configs:
      - targets: 
          - 'localhost:8080'  # Miner API endpoint
    metrics_path: '/api/metrics'
    scrape_interval: 5s
    scrape_timeout: 3s

  # Marketplace Backend Metrics
  - job_name: 'blacksilk-marketplace'
    static_configs:
      - targets:
          - 'localhost:3000'  # Marketplace backend
    metrics_path: '/api/metrics'
    scrape_interval: 30s

  # System Metrics (Node Exporter)
  - job_name: 'node-exporter'
    static_configs:
      - targets:
          - 'localhost:9100'
    scrape_interval: 15s

  # Network Health Monitors
  - job_name: 'blacksilk-network-monitor'
    static_configs:
      - targets:
          - 'monitor.blacksilk.network:9090'
          - 'testnet-monitor.blacksilk.network:9090'
    scrape_interval: 30s
    honor_labels: true

  # External Seed Node Monitoring
  - job_name: 'blacksilk-seed-nodes'
    dns_sd_configs:
      - names:
          - 'seeds.blacksilk.network'
          - 'testnet-seeds.blacksilk.network'
        type: 'A'
        port: 9333
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'blacksilk-exporter:9115'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

# Remote write for long-term storage (optional)
# remote_write:
#   - url: "https://prometheus-remote-write.example.com/api/v1/write"
#     basic_auth:
#       username: "${REMOTE_WRITE_USERNAME}"
#       password: "${REMOTE_WRITE_PASSWORD}"

# Recording rules for performance optimization
recording_rules:
  - name: blacksilk.rules
    interval: 30s
    rules:
      - record: blacksilk:node_height_lag
        expr: max(blacksilk_chain_height) - blacksilk_chain_height
      
      - record: blacksilk:network_hashrate_5m
        expr: rate(blacksilk_total_hashes[5m])
      
      - record: blacksilk:tx_throughput_5m
        expr: rate(blacksilk_transactions_total[5m])
      
      - record: blacksilk:block_time_avg_1h
        expr: rate(blacksilk_blocks_total[1h]) * 60
