//! The fixture of the fingerprint's transaction samples
//! (`src/fingerprint_fixture.txt`, `blacksilk_node::fingerprint::Fixture`):
//! a transfer with two inputs and three outputs, signed under
//! `fixture_rules()`, the coinbase that created its first real input, and
//! its ring members' records.
//!
//! The fixture is pinned data: the rules fingerprint lists the verdicts of
//! `validate_transfer` on it and on one variant per error class. It is
//! regenerated only when a reviewed rule change invalidates it:
//!
//! ```text
//! cargo test --release -p blacksilk-node --test fingerprint_fixture -- --ignored
//! ```
//!
//! which rewrites the file (deterministically: a fixed seed). A regenerated
//! fixture changes the rules fingerprint and needs the re-pin procedure
//! (docs/reviews/v3-consensus-changes.md#fingerprint-v3).

use blacksilk_crypto::keys::{SubaddressIndex, SubaddressTable, WalletKeys};
use blacksilk_crypto::{Point, RistrettoPoint, Scalar};
use blacksilk_node::fingerprint::{fixture_rules, Fixture};
use blacksilk_tx::builder::{
    build_coinbase, build_transfer, standard_fee, Decoy, InputPlan, Payment,
};
use blacksilk_tx::params::{COINBASE_MATURITY, RING_SIZE, SPENDABLE_AGE};
use blacksilk_tx::scan::scan_block;
use blacksilk_tx::types::OutputKey;
use blacksilk_tx::Transaction;
use rand_chacha::rand_core::SeedableRng;
use rand_chacha::ChaCha20Rng;

/// The height the transfer is validated at: both coinbase inputs (heights 1
/// and 2) and every decoy (height 50) are spendable.
const HEIGHT: u64 = 100;
/// Height of the decoys (plain outputs).
const DECOY_HEIGHT: u64 = 50;

fn point(n: u64) -> Point {
    Point::from_point(RistrettoPoint::mul_base(&Scalar::from(n)))
}

fn hex(b: &[u8]) -> String {
    b.iter().map(|x| format!("{x:02x}")).collect()
}

/// Builds the fixture text.
fn generate() -> String {
    const { assert!(HEIGHT >= 2 + COINBASE_MATURITY && HEIGHT >= DECOY_HEIGHT + SPENDABLE_AGE) };
    let mut rng = ChaCha20Rng::seed_from_u64(0x0B5F_1A6E);
    let (keys, _) = WalletKeys::generate(&mut rng);
    let (payee, _) = WalletKeys::generate(&mut rng);
    let table = SubaddressTable::new(keys.view_keys(), 1, 1);
    let me = keys.address(SubaddressIndex::new(0, 0));

    // Two coinbases paying the wallet (global indices 0 and 1).
    let mut coinbases = Vec::new();
    let mut owned = Vec::new();
    for (height, amount) in [(1u64, 5_000_000_000u64), (2, 7_000_000_000)] {
        let cb = build_coinbase(
            height,
            &[Payment {
                address: me,
                amount,
            }],
            &keys.hedge_secret(),
            &mut rng,
        )
        .expect("a coinbase");
        let txs = [Transaction::Coinbase(cb)];
        let report = scan_block(keys.view_keys(), &table, &txs, height, height - 1);
        assert_eq!(report.owned.len(), 1);
        owned.push(report.owned[0].clone());
        coinbases.push(txs[0].clone());
    }

    // Fifteen decoys per input: plain outputs at global indices 2 and up.
    let decoy = |i: u64| Decoy {
        global_index: i,
        key: OutputKey {
            one_time_key: point(1_000 + i),
            commitment: point(2_000 + i),
        },
    };
    let decoys_per_input = RING_SIZE as u64 - 1;
    let plans: Vec<InputPlan> = owned
        .iter()
        .enumerate()
        .map(|(k, o)| InputPlan {
            real: o.into(),
            decoys: (0..decoys_per_input)
                .map(|j| decoy(2 + k as u64 * decoys_per_input + j))
                .collect(),
        })
        .collect();
    let rules = fixture_rules();
    let payments = [
        Payment {
            address: payee.address(SubaddressIndex::new(0, 0)),
            amount: 3_000_000_000,
        },
        Payment {
            address: payee.address(SubaddressIndex::new(0, 1)),
            amount: 4_000_000_000,
        },
    ];
    let fee = standard_fee(2, 3, &rules);
    let transfer = build_transfer(&keys, plans.clone(), &payments, &me, fee, &rules, &mut rng)
        .expect("the fixture transfer");
    assert_eq!((transfer.inputs.len(), transfer.outputs.len()), (2, 3));

    let mut text = String::from(
        "# The fixture of the fingerprint's transaction samples (node/src/fingerprint.rs).\n\
         # Generated by node/tests/fingerprint_fixture.rs; pinned data, do not edit.\n",
    );
    text.push_str(&format!("height {HEIGHT}\n"));
    text.push_str(&format!("coinbase {}\n", hex(&coinbases[0].encode())));
    text.push_str(&format!(
        "transfer {}\n",
        hex(&Transaction::from(transfer).encode())
    ));
    for (k, o) in owned.iter().enumerate() {
        text.push_str(&format!(
            "output {} {} 1 {} {}\n",
            o.global_index,
            k + 1,
            hex(o.key.one_time_key.bytes()),
            hex(o.key.commitment.bytes())
        ));
    }
    for plan in &plans {
        for d in &plan.decoys {
            text.push_str(&format!(
                "output {} {DECOY_HEIGHT} 0 {} {}\n",
                d.global_index,
                hex(d.key.one_time_key.bytes()),
                hex(d.key.commitment.bytes())
            ));
        }
    }
    text
}

/// Rewrites `src/fingerprint_fixture.txt` (a reviewed rule change only).
#[test]
#[ignore]
fn regenerate_the_fingerprint_fixture() {
    let text = generate();
    let parsed = Fixture::parse(&text).expect("the generated fixture parses");
    assert_eq!(parsed.outputs.len(), 2 * RING_SIZE);
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/src/fingerprint_fixture.txt");
    std::fs::write(path, text).expect("write the fixture");
}

/// The checked-in fixture parses, has the documented shape, and is valid
/// under the fixture rules at its height (so every verdict sample is a
/// variant of a valid transfer).
#[test]
fn the_fixture_is_a_valid_transfer() {
    let f = Fixture::get();
    assert_eq!((f.transfer.inputs.len(), f.transfer.outputs.len()), (2, 3));
    assert_eq!(f.outputs.len(), 2 * RING_SIZE);
    assert!(matches!(f.coinbase, Transaction::Coinbase(_)));
    for input in &f.transfer.inputs {
        for i in input.ring {
            assert!(f.outputs.contains_key(&i), "ring member {i}");
        }
    }
}
