//! Mempool admission and block templates.

use super::{ChainManager, Template};
use crate::emission::block_reward;
use crate::mempool::{MempoolError, Origin, COINBASE_RESERVE};
use crate::sync_policy;
use blacksilk_consensus::Hash;
use blacksilk_tx::types::Transaction;

impl ChainManager {
    /// Validates a transaction from a peer for the next block without adding
    /// it (Dandelion stem phase, docs/p2p.md §8). The recently-expired guard
    /// does not apply ([`Origin::Peer`]).
    pub fn check_tx(&self, tx: &Transaction) -> Result<Hash, MempoolError> {
        self.check_from(tx, Origin::Peer)
    }

    /// Validates a transaction originated here (`/tx`, a wallet submitting
    /// through this node) for the next block without adding it, before it
    /// enters the stem. Refused as `Expired` while this node expired it
    /// recently ([`Origin::Local`], RTW1B-1).
    pub fn check_local_tx(&self, tx: &Transaction) -> Result<Hash, MempoolError> {
        self.check_from(tx, Origin::Local)
    }

    fn check_from(&self, tx: &Transaction, origin: Origin) -> Result<Hash, MempoolError> {
        let next = self.height() + 1;
        self.mempool
            .check(tx, &self.state, next, &self.rules_at(next), origin)
    }

    /// Adds a transaction from a peer (relay, or a stem transaction fluffed
    /// here) to the mempool (valid for the next block). The recently-expired
    /// guard does not apply ([`Origin::Peer`]).
    pub fn submit_tx(&mut self, tx: Transaction) -> Result<Hash, MempoolError> {
        self.submit_from(tx, Origin::Peer)
    }

    /// Adds a transaction originated here (`/tx` without P2P) to the
    /// mempool. Refused as `Expired` while this node expired it recently
    /// ([`Origin::Local`], RTW1B-1).
    pub fn submit_local_tx(&mut self, tx: Transaction) -> Result<Hash, MempoolError> {
        self.submit_from(tx, Origin::Local)
    }

    fn submit_from(&mut self, tx: Transaction, origin: Origin) -> Result<Hash, MempoolError> {
        let next = self.height() + 1;
        let rules = self.rules_at(next);
        self.mempool.add(tx, &self.state, next, &rules, origin)
    }

    /// `G(h)`: coins generated by blocks `1..h`. Rewards depend only on height, so
    /// this is the same on every branch; heights above the tip are extrapolated.
    fn generated_before(&self, height: u64) -> u64 {
        if let Some(g) = self.generated.get(height.saturating_sub(1) as usize) {
            return if height == 0 { 0 } else { *g };
        }
        let mut g = self.generated();
        for h in self.height() + 1..height {
            g += block_reward(h, g);
        }
        g
    }

    /// Template for a coinbase-only child of any valid known block (e.g. to extend
    /// a side branch). Mempool transactions are only offered on the tip.
    pub fn template_on(&self, parent: &Hash) -> Option<Template> {
        let t = self.headers.template_on(*parent)?;
        Some(Template {
            height: t.height,
            prev_id: t.prev_id,
            difficulty: t.difficulty,
            seed_id: t.seed_id,
            min_timestamp: t.min_timestamp,
            version: t.version,
            reward: block_reward(t.height, self.generated_before(t.height)),
            fees: 0,
            txs: Vec::new(),
        })
    }

    /// Template for the next block on the connected tip.
    pub fn template(&self) -> Template {
        let t = self
            .headers
            .template_on(self.tip_id())
            .expect("connected tip is a valid header");
        let reward = block_reward(t.height, self.generated());
        let rules = self.rules_at(t.height);
        // The pool holds only transactions validated under the next block's
        // rules (`finish_sync` flushes it at an activation); checked here too,
        // so that a template never offers transactions of another rule set.
        let txs = if self.mempool.validated_under() == Some(rules.domain()) {
            self.mempool.select(
                t.height,
                rules.max_block_weight.saturating_sub(COINBASE_RESERVE),
                blacksilk_tx::validate::ChainView::px_pool(&self.state),
                self.state.px().free_leaves(),
            )
        } else {
            Vec::new()
        };
        let fees = txs.iter().map(Transaction::fee).sum();
        Template {
            height: t.height,
            prev_id: t.prev_id,
            difficulty: t.difficulty,
            seed_id: t.seed_id,
            min_timestamp: t.min_timestamp,
            version: t.version,
            reward,
            fees,
            txs,
        }
    }

    /// Whether the node counts as caught up at the local time `now`
    /// ([`sync_policy::caught_up`]): no bounded drain in progress, the best
    /// header at most [`sync_policy::TEMPLATE_SYNC_SLACK`] blocks ahead of
    /// the connected tip, and the tip recent ([`sync_policy::max_tip_age`];
    /// no clock rule on regtest).
    pub fn caught_up(&self, now: u64) -> bool {
        sync_policy::caught_up(
            self.sync_pending(),
            self.height(),
            self.header_height(),
            self.tip_header().timestamp,
            now,
            sync_policy::max_tip_age(&self.params),
        )
    }

    /// Whether the template gate's catch-up latch is set (RTW3-1): the node
    /// was caught up at some clock reading since it opened
    /// ([`Self::update_template_latch`]), or the operator set it
    /// ([`Self::set_template_latch`]). It is never cleared.
    pub fn template_latched(&self) -> bool {
        self.template_latched
    }

    /// Sets the catch-up latch if the node is caught up at `now`
    /// ([`Self::caught_up`]). Called with the clock reading of every block
    /// submission (`submit_block`, `submit_block_bounded`) and header batch
    /// (`accept_headers`), before the input is processed, and by `/template`
    /// before it decides. Evaluating before the input means a synced node
    /// latches on the state it had when the next block or header batch
    /// arrived, whatever that input adds.
    pub fn update_template_latch(&mut self, now: u64) {
        if !self.template_latched && self.caught_up(now) {
            self.template_latched = true;
            log::info!(
                "caught up at height {}: block templates are served from now on",
                self.height()
            );
        }
    }

    /// Sets the catch-up latch without the checks (the node's
    /// `--mine-from-stale-tip`): for the first blocks of a network whose
    /// genesis is older than the tip-age bound, or restarting mining after
    /// every miner of the network stopped. Mid-drain templates stay refused.
    pub fn set_template_latch(&mut self) {
        self.template_latched = true;
        self.publish_summary();
    }

    /// Whether this node serves block templates at the local time `now`
    /// ([`sync_policy::template_ready`]): never while a bounded drain is in
    /// progress, and before the catch-up latch sets only when
    /// [`Self::caught_up`]. Once latched, a header lead never closes the
    /// gate (RTW3-1). `/template` answers `503` otherwise. Read-only: it
    /// does not set the latch ([`Self::update_template_latch`] does).
    pub fn template_ready(&self, now: u64) -> bool {
        sync_policy::template_ready(
            self.sync_pending(),
            self.template_latched,
            self.caught_up(now),
        )
    }

    /// The RandomX key that blocks after a template at `height` on `prev_id`
    /// switch to, while it is announced (the `seed_lag` heights before the
    /// switch, [`sync_policy::next_seed_height`]): the id of that key block
    /// on `prev_id`'s branch. `None` outside the window, or for a parent that
    /// is unknown or not at `height - 1`. The miner builds the next key's
    /// context from it; the template's own `seed_id` stays the only key a
    /// block is hashed with.
    pub fn next_seed_id(&self, height: u64, prev_id: &Hash) -> Option<Hash> {
        let p = self.params();
        sync_policy::next_seed_height(height, p.seed_epoch, p.seed_lag)?;
        let parent = self.headers.header(prev_id)?;
        if parent.height + 1 != height {
            return None;
        }
        Some(self.headers.seed_id_for(*prev_id, height + p.seed_lag))
    }
}

#[cfg(test)]
mod tests {
    //! The template readiness gate (dossier 09 M9-2, RTW3-1) and the next
    //! RandomX key (09 I3), on a regtest chain with a short key epoch (16,
    //! lag 4: the first switch at height 21, key = block 16), and on
    //! testnet parameters where the tip-age rule applies.
    use super::*;
    use crate::block::Block;
    use crate::store::MemoryStore;
    use blacksilk_consensus::merkle::tx_root;
    use blacksilk_consensus::{BlockHeader, ChainParams, PowFunction};
    use blacksilk_crypto::keys::{SubaddressIndex, WalletKeys};
    use blacksilk_tx::builder::{build_coinbase, Payment};
    use blacksilk_tx::params::TxRules;
    use rand_chacha::rand_core::SeedableRng;
    use rand_chacha::ChaCha20Rng;
    use std::sync::Arc;

    struct ZeroPow;
    impl PowFunction for ZeroPow {
        fn pow_hash(&self, _: &Hash, _: &[u8]) -> Hash {
            [0; 32]
        }
    }

    fn params() -> blacksilk_consensus::ChainParams {
        let mut p = ChainParams::regtest();
        p.seed_epoch = 16;
        p.seed_lag = 4;
        p
    }

    fn open() -> ChainManager {
        open_with(params())
    }

    fn open_with(p: ChainParams) -> ChainManager {
        ChainManager::open(
            p.clone(),
            TxRules::for_chain(&p),
            Arc::new(ZeroPow),
            Box::<MemoryStore>::default(),
            [3; 32],
        )
        .unwrap()
    }

    const NOW: u64 = u64::MAX / 2;
    const SLACK: u64 = sync_policy::TEMPLATE_SYNC_SLACK;

    /// `n` coinbase-only blocks on `parent`, connected on `m`; `nonce`
    /// tells branches apart.
    fn branch(m: &mut ChainManager, parent: Hash, n: usize, nonce: u64) -> Vec<Block> {
        let mut rng = ChaCha20Rng::seed_from_u64(nonce);
        let (keys, _) = WalletKeys::generate(&mut rng);
        let genesis_time = m.params().genesis.timestamp;
        let mut prev = parent;
        let mut out = Vec::new();
        for _ in 0..n {
            let t = m.template_on(&prev).unwrap();
            let cb = build_coinbase(
                t.height,
                &[Payment {
                    address: keys.address(SubaddressIndex::PRIMARY),
                    amount: t.reward,
                }],
                &keys.hedge_secret(),
                &mut rng,
            )
            .unwrap();
            let txs = vec![Transaction::Coinbase(cb)];
            let ids: Vec<Hash> = txs.iter().map(Transaction::hash).collect();
            let header = BlockHeader {
                version: t.version,
                height: t.height,
                prev_id: prev,
                timestamp: t.min_timestamp.max(genesis_time + 120 * t.height),
                difficulty: t.difficulty,
                tx_root: tx_root(&ids),
                nonce,
            };
            let b = Block { header, txs };
            m.submit_block(b.clone(), NOW).unwrap();
            prev = b.id(m.params().network_id);
            out.push(b);
        }
        out
    }

    /// Testnet (tip-age bound 24 × 120 s): a node catching up refuses
    /// templates while its bodies are more than 2 blocks behind its best
    /// header (even with a recent tip) and while its tip is old (even with
    /// no header gap). Once caught up at a clock reading it latches, and
    /// from then on neither rule refuses, however far headers run ahead.
    #[test]
    fn a_node_refuses_templates_until_it_first_catches_up_then_latches() {
        let mut src = open_with(ChainParams::testnet());
        let g = src.tip_id();
        let blocks = branch(&mut src, g, 13, 1);
        let at = |i: usize| blocks[i].header.timestamp;
        let late = at(12) + 100_000;
        let mut m = open_with(ChainParams::testnet());
        let age = sync_policy::max_tip_age(m.params()).unwrap();
        assert_eq!(age, 24 * 120);
        assert!(!m.template_ready(late), "an old genesis is not caught up");
        m.update_template_latch(late);
        assert!(!m.template_latched());
        let headers: Vec<BlockHeader> = blocks[..10].iter().map(|b| b.header).collect();
        m.accept_headers(&headers, late).unwrap();
        for b in &blocks[..7] {
            m.submit_block(b.clone(), late).unwrap();
        }
        assert_eq!((m.height(), m.header_height()), (7, 10));
        assert!(!m.template_ready(at(6)), "a header gap of 3, recent tip");
        m.update_template_latch(at(6));
        assert!(!m.template_latched());
        m.submit_block(blocks[7].clone(), late).unwrap();
        assert_eq!(m.header_height() - m.height(), SLACK);
        assert!(m.template_ready(at(7)), "a header gap of 2, recent tip");
        assert!(m.template_ready(at(7) + age), "at the tip-age bound");
        assert!(!m.template_ready(at(7) + age + 1), "an old tip");
        assert!(!m.template_latched(), "only a clock reading latches");
        // The latch sets on the state before the input: the node is caught
        // up at `at(9)` (tip 240 s old, header gap 2) when these headers
        // arrive, and the lead they open does not matter.
        let more: Vec<BlockHeader> = blocks[10..].iter().map(|b| b.header).collect();
        m.accept_headers(&more, at(9)).unwrap();
        assert!(m.template_latched());
        assert_eq!(m.header_height() - m.height(), 5);
        assert!(m.template_ready(late), "latched: no header or clock rule");
        assert!(m.summary().template_latched);
        assert!(m.summary().template_ready(late));
    }

    /// Regtest has no clock rule, so a fresh node latches at its first
    /// input (Bitcoin Core serves templates on test chains without its
    /// initial-download check). A bounded drain refuses templates between
    /// its steps, latched or not.
    #[test]
    fn templates_wait_for_a_bounded_drain_even_when_latched() {
        let mut src = open();
        let g = src.tip_id();
        let blocks = branch(&mut src, g, 20, 1);
        let mut m = open();
        assert!(
            m.template_ready(NOW),
            "a lone node at genesis serves templates"
        );
        let headers: Vec<BlockHeader> = blocks.iter().map(|b| b.header).collect();
        m.accept_headers(&headers, NOW).unwrap();
        assert!(
            m.template_latched(),
            "caught up at genesis before the headers"
        );
        assert!(m.template_ready(NOW), "a header gap of 20, latched");
        for b in blocks[1..].iter().rev() {
            m.submit_block_bounded(b.clone(), NOW, 8).unwrap();
        }
        assert_eq!(m.height(), 0, "the bodies wait for block 1");
        m.submit_block_bounded(blocks[0].clone(), NOW, 8).unwrap();
        assert!(m.sync_pending(), "the drain is split into steps");
        assert!(!m.template_ready(NOW), "mid-drain");
        let mut steps = 0;
        while !m.sync_step(8) {
            steps += 1;
            assert!(!m.template_ready(NOW), "mid-drain, step {steps}");
        }
        assert_eq!(m.height(), 20);
        assert!(m.template_ready(NOW), "the drain ended");
    }

    /// `--mine-from-stale-tip`: the operator's latch serves templates on an
    /// old testnet tip, but not mid-drain.
    #[test]
    fn the_operator_latch_serves_templates_on_an_old_tip() {
        let mut m = open_with(ChainParams::testnet());
        assert!(!m.template_ready(NOW));
        let seq = m.summary().seq;
        m.set_template_latch();
        assert!(m.template_latched());
        assert!(m.template_ready(NOW));
        assert!(m.summary().seq > seq, "published");
        assert!(m.summary().template_ready(NOW));
    }

    /// `next_seed_id` is announced exactly for the `lag` template heights
    /// before a switch, equals the key of the first template after it, and
    /// follows the parent's branch.
    #[test]
    fn the_next_key_is_announced_in_the_lag_window() {
        let mut m = open();
        let g = m.tip_id();
        let main = branch(&mut m, g, 24, 1);
        let nid = m.params().network_id;
        let id = |b: &Block| b.id(nid);
        let key16 = id(&main[15]);
        for h in 1..=24u64 {
            let prev = if h == 1 { g } else { id(&main[h as usize - 2]) };
            let expected = (17..=20).contains(&h).then_some(key16);
            assert_eq!(m.next_seed_id(h, &prev), expected, "template height {h}");
        }
        let t = m.template_on(&id(&main[19])).unwrap();
        assert_eq!(
            (t.height, t.seed_id),
            (21, key16),
            "the key after the switch"
        );
        // A side branch forking at 15 has its own block 16: the next key on
        // it is that block, not the main chain's.
        let side = branch(&mut m, id(&main[14]), 3, 2);
        assert_eq!(m.height(), 24, "the side branch is lighter");
        assert_eq!(
            m.next_seed_id(19, &id(&side[2])),
            Some(id(&side[0])),
            "the side branch's block 16"
        );
        assert_ne!(id(&side[0]), key16);
        // A parent at the wrong height or an unknown parent: nothing.
        assert_eq!(m.next_seed_id(19, &id(&main[16])), None);
        assert_eq!(m.next_seed_id(18, &[9; 32]), None);
    }
}
