//! Mempool admission and block templates.

use super::{ChainManager, Template};
use crate::emission::block_reward;
use crate::mempool::{MempoolError, Origin, COINBASE_RESERVE};
use blacksilk_consensus::Hash;
use blacksilk_tx::types::Transaction;

impl ChainManager {
    /// Validates a transaction from a peer for the next block without adding
    /// it (Dandelion stem phase, docs/p2p.md §8). The recently-expired guard
    /// does not apply ([`Origin::Peer`]).
    pub fn check_tx(&self, tx: &Transaction) -> Result<Hash, MempoolError> {
        self.check_from(tx, Origin::Peer)
    }

    /// Validates a transaction originated here (`/tx`, a wallet submitting
    /// through this node) for the next block without adding it, before it
    /// enters the stem. Refused as `Expired` while this node expired it
    /// recently ([`Origin::Local`], RTW1B-1).
    pub fn check_local_tx(&self, tx: &Transaction) -> Result<Hash, MempoolError> {
        self.check_from(tx, Origin::Local)
    }

    fn check_from(&self, tx: &Transaction, origin: Origin) -> Result<Hash, MempoolError> {
        let next = self.height() + 1;
        self.mempool
            .check(tx, &self.state, next, &self.rules_at(next), origin)
    }

    /// Adds a transaction from a peer (relay, or a stem transaction fluffed
    /// here) to the mempool (valid for the next block). The recently-expired
    /// guard does not apply ([`Origin::Peer`]).
    pub fn submit_tx(&mut self, tx: Transaction) -> Result<Hash, MempoolError> {
        self.submit_from(tx, Origin::Peer)
    }

    /// Adds a transaction originated here (`/tx` without P2P) to the
    /// mempool. Refused as `Expired` while this node expired it recently
    /// ([`Origin::Local`], RTW1B-1).
    pub fn submit_local_tx(&mut self, tx: Transaction) -> Result<Hash, MempoolError> {
        self.submit_from(tx, Origin::Local)
    }

    fn submit_from(&mut self, tx: Transaction, origin: Origin) -> Result<Hash, MempoolError> {
        let next = self.height() + 1;
        let rules = self.rules_at(next);
        self.mempool.add(tx, &self.state, next, &rules, origin)
    }

    /// `G(h)`: coins generated by blocks `1..h`. Rewards depend only on height, so
    /// this is the same on every branch; heights above the tip are extrapolated.
    fn generated_before(&self, height: u64) -> u64 {
        if let Some(g) = self.generated.get(height.saturating_sub(1) as usize) {
            return if height == 0 { 0 } else { *g };
        }
        let mut g = self.generated();
        for h in self.height() + 1..height {
            g += block_reward(h, g);
        }
        g
    }

    /// Template for a coinbase-only child of any valid known block (e.g. to extend
    /// a side branch). Mempool transactions are only offered on the tip.
    pub fn template_on(&self, parent: &Hash) -> Option<Template> {
        let t = self.headers.template_on(*parent)?;
        Some(Template {
            height: t.height,
            prev_id: t.prev_id,
            difficulty: t.difficulty,
            seed_id: t.seed_id,
            min_timestamp: t.min_timestamp,
            version: t.version,
            reward: block_reward(t.height, self.generated_before(t.height)),
            fees: 0,
            txs: Vec::new(),
        })
    }

    /// Template for the next block on the connected tip.
    pub fn template(&self) -> Template {
        let t = self
            .headers
            .template_on(self.tip_id())
            .expect("connected tip is a valid header");
        let reward = block_reward(t.height, self.generated());
        let rules = self.rules_at(t.height);
        // The pool holds only transactions validated under the next block's
        // rules (`finish_sync` flushes it at an activation); checked here too,
        // so that a template never offers transactions of another rule set.
        let txs = if self.mempool.validated_under() == Some(rules.domain()) {
            self.mempool.select(
                t.height,
                rules.max_block_weight.saturating_sub(COINBASE_RESERVE),
                blacksilk_tx::validate::ChainView::px_pool(&self.state),
                self.state.px().free_leaves(),
            )
        } else {
            Vec::new()
        };
        let fees = txs.iter().map(Transaction::fee).sum();
        Template {
            height: t.height,
            prev_id: t.prev_id,
            difficulty: t.difficulty,
            seed_id: t.seed_id,
            min_timestamp: t.min_timestamp,
            version: t.version,
            reward,
            fees,
            txs,
        }
    }
}
