[package]
name = "blacksilk-miner"
version = "0.1.0"
edition = "2021"

authors = ["BlackSilk Contributors"]
description = "Standalone miner for BlackSilk blockchain"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
tokio = { version = "1.32", features = ["full"] }
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
randomx-rs = "0.4"
crossbeam-channel = "0.5"
hex = "0.4"
num_cpus = "1.16"