[package]
name = "blacksilk-exporter"
version = "0.1.0"
edition = "2021"

[dependencies]
prometheus = "0.13"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
warp = "0.3"
anyhow = "1.0"
