#!/usr/bin/env python3
"""Independent golden vectors for `max_weight(n_in, n_out)` and the exact v1 fee.

TEST TOOLING ONLY, NOT CORE. Nothing in the node, wallet or miner runs this
file. It produces `tx/tests/data/max_weight.txt`, which `tx/tests/exact_fee.rs`
checks against the Rust implementation (`blacksilk_tx::params::max_weight`,
`TxRules::standard_fee`) for every shape.

Independence: nothing here is transcribed from the Rust code. The formula is
derived from the specification:
- docs/transactions.md §4.1 (a varint is at most 10 bytes; points and scalars
  are 32 bytes) and §4.2 (the transfer layout: prefix, base, prunable);
- docs/transactions.md §7 (a BP+ proof over k commitments has 2*log2(64*M) + 6
  elements, M = k rounded up to a power of two);
- docs/transactions.md §6.1 / §4.2 (a CLSAG is c0, s[16] and D: 18 elements);
- docs/transactions.md §8.4 (weight = size + clawback, the clawback
  (320*M - bp_size) * 4 / 5 when M > 2) and T8 (fee = FEE_PER_WEIGHT *
  max_weight, FEE_PER_WEIGHT = 20, docs/blocks.md §5);
- docs/px.md §11.5 and docs/transactions.md B6: the v1 part of a PX
  transaction may have n_out = 0 or 1 hidden outputs (no range proof when 0).

`max_weight` is the weight of a transfer of that shape with every varint at
its 10-byte maximum: version, input count, the 16 ring entries of each input,
output count and fee. The kind byte is 1 byte.

Usage:
  python tools/vectors/max_weight.py            # print the vector file
  python tools/vectors/max_weight.py --write    # rewrite tx/tests/data/max_weight.txt
  python tools/vectors/max_weight.py --check    # compare with the committed file

Python standard library only.
"""

import argparse
import os
import sys

VARINT_MAX = 10
ELEMENT = 32  # a point or a scalar
RING_SIZE = 16
FEE_PER_WEIGHT = 20
MAX_INPUTS = 64
MAX_OUTPUTS = 16

# One output of a transfer: one-time key, ephemeral key, view tag, commitment,
# encrypted amount, encrypted anchor (§4.2).
OUTPUT_BYTES = ELEMENT + ELEMENT + 1 + ELEMENT + 8 + 16
# One input in the prefix: key image, 16 ring varints.
INPUT_PREFIX_BYTES = ELEMENT + RING_SIZE * VARINT_MAX
# A CLSAG: c0, s[16], D.
CLSAG_BYTES = (1 + RING_SIZE + 1) * ELEMENT


def next_pow2(x):
    m = 1
    while m < x:
        m *= 2
    return m


def log2_exact(x):
    r = 0
    while (1 << r) < x:
        r += 1
    assert (1 << r) == x
    return r


def bp_size(k):
    """Encoded BP+ proof size over k commitments; 0 when there is no proof."""
    if k == 0:
        return 0
    m = next_pow2(k)
    rounds = log2_exact(64 * m)
    return ELEMENT * (2 * rounds + 6)


def max_weight(n, k):
    prefix = (
        VARINT_MAX  # version
        + 1  # kind
        + VARINT_MAX  # input count
        + n * INPUT_PREFIX_BYTES
        + VARINT_MAX  # output count
        + k * OUTPUT_BYTES
        + VARINT_MAX  # fee
    )
    base = n * ELEMENT  # pseudo-outputs
    bp = bp_size(k)
    prunable = bp + n * CLSAG_BYTES
    size = prefix + base + prunable
    m = next_pow2(max(k, 1))
    if m <= 2:
        return size
    clawback = max(320 * m - bp, 0) * 4 // 5
    return size + clawback


def table():
    lines = [
        "# max_weight(n_in, n_out) and the exact v1 fee FEE_PER_WEIGHT * max_weight.",
        "# Generated by tools/vectors/max_weight.py (independent of the Rust code).",
        "# Columns: n_in n_out max_weight fee. n_out = 0 and 1 are PX v1-part shapes.",
    ]
    for n in range(1, MAX_INPUTS + 1):
        for k in range(0, MAX_OUTPUTS + 1):
            w = max_weight(n, k)
            lines.append(f"{n} {k} {w} {FEE_PER_WEIGHT * w}")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    here = os.path.dirname(os.path.abspath(__file__))
    path = os.path.normpath(os.path.join(here, "..", "..", "tx", "tests", "data", "max_weight.txt"))
    text = table()
    # Spot checks against values worked out by hand from the formula above.
    assert max_weight(1, 2) == 1723, max_weight(1, 2)
    if args.write:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", newline="\n") as f:
            f.write(text)
        print(f"wrote {path}")
    elif args.check:
        with open(path, newline="") as f:
            if f.read() != text:
                print(f"{path} differs from the generated table", file=sys.stderr)
                sys.exit(1)
        print("ok")
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
