#!/usr/bin/env python3
"""Independent vectors for the v3 header (172 bytes), its mining blob and the output MMR.

TEST TOOLING ONLY, NOT CORE. Nothing in the node, wallet or miner runs this file.
It produces `tx/tests/data/output_mmr.txt`, which `tx/tests/output_mmr_vectors.rs`
checks against the Rust implementation (`blacksilk_tx::mmr`), and prints on stdout
the header and genesis values pinned in `consensus/tests/golden.rs` and
`consensus/src/params.rs`.

Independence: written from docs/consensus.md section 2 (header layout, block id),
section 7.1 (the output range) and docs/crypto conventions (domain tags), not from
the Rust code. The range is computed from its recursive definition (perfect
subtrees of the binary decomposition of n), not with the incremental frontier the
Rust code uses. The empty PX root of the genesis header is read from
`px/tests/data/hk_vectors.txt` (`empty.32`), the output of the independent
Poseidon2 script `tools/vectors/poseidon2_hk.py`.

The definitions, restated:
  tag(name)   = u8(len("BlackSilk/v1/" + name)) || "BlackSilk/v1/" + name
  H32(name,x) = Blake2b-256(tag(name) || x)
  leaf(o)     = H32("output-mmr/leaf", one_time_key || commitment || LE64(height) || u8(coinbase))
  node(l, r)  = H32("output-mmr/node", l || r)
  peaks(n)    = roots of the perfect subtrees of n's binary decomposition, largest first
  root(0)     = 32 zero bytes
  root(n)     = H32("output-mmr/root", LE64(n) || peaks(n)...)
  header      = LE32 version || LE64 height || prev_id || LE64 timestamp || LE64 difficulty
                || tx_root || LE64 output_count || output_root || px_root || LE64 nonce
  block id    = Blake2b-256("BlackSilk/block-id" || LE32(network_id) || header)
  mining hash = H32("mining-hash", LE32(network_id) || header[0..164])
  pow blob    = "BSilk/1" || mining hash || LE64(nonce)   (47 bytes, nonce at 39)

Usage:
  python tools/vectors/output_mmr.py            # print the vector file and the header values
  python tools/vectors/output_mmr.py --write    # rewrite tx/tests/data/output_mmr.txt
  python tools/vectors/output_mmr.py --check    # compare with the committed file

Python standard library only.
"""

import argparse
import hashlib
import os
import struct
import sys

PREFIX = b"BlackSilk/v1/"
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))
DATA = os.path.join(ROOT, "tx", "tests", "data", "output_mmr.txt")
HK = os.path.join(ROOT, "px", "tests", "data", "hk_vectors.txt")


def h32(name, *parts):
    tag = PREFIX + name.encode()
    assert len(tag) <= 255
    d = hashlib.blake2b(digest_size=32)
    d.update(bytes([len(tag)]) + tag)
    for p in parts:
        d.update(p)
    return d.digest()


def le64(x):
    return struct.pack("<Q", x)


def leaf(key, commitment, height, coinbase):
    return h32("output-mmr/leaf", key, commitment, le64(height), bytes([1 if coinbase else 0]))


def node(l, r):
    return h32("output-mmr/node", l, r)


def tree(xs):
    """The root of a perfect subtree of 2^k leaf hashes."""
    if len(xs) == 1:
        return xs[0]
    half = len(xs) // 2
    return node(tree(xs[:half]), tree(xs[half:]))


def peaks(leaves):
    n = len(leaves)
    out = []
    at = 0
    for h in range(63, -1, -1):
        if (n >> h) & 1:
            size = 1 << h
            out.append(tree(leaves[at:at + size]))
            at += size
    assert at == n
    return out


def root(leaves):
    n = len(leaves)
    if n == 0:
        return bytes(32)
    return h32("output-mmr/root", le64(n), *peaks(leaves))


def vector_output(i):
    """The i-th vector output: arbitrary 32-byte strings (the leaf hashes bytes,
    whatever they encode), a height and a coinbase flag."""
    key = hashlib.blake2b(b"mmr-vector/key" + le64(i), digest_size=32).digest()
    commitment = hashlib.blake2b(b"mmr-vector/commitment" + le64(i), digest_size=32).digest()
    return key, commitment, i // 3, i % 3 == 0


SIZES = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 15, 16, 17, 31, 32, 33, 63, 64, 65, 100, 255, 256, 257, 1000]


def table():
    n_max = max(SIZES)
    outs = [vector_output(i) for i in range(n_max)]
    leaves = [leaf(*o) for o in outs]
    lines = [
        "# The output Merkle mountain range (docs/consensus.md section 7.1).",
        "# Generated by tools/vectors/output_mmr.py (independent of the Rust code).",
        "# Output i: key = Blake2b-256(\"mmr-vector/key\" || LE64 i), commitment =",
        "# Blake2b-256(\"mmr-vector/commitment\" || LE64 i), height = i // 3, coinbase = i % 3 == 0.",
        "# leaf <i> <hex>: leaf(output i); peaks <n> <hex,...>: peaks of outputs 0..n;",
        "# root <n> <hex>: root of outputs 0..n.",
    ]
    for i in range(6):
        lines.append(f"leaf {i} {leaves[i].hex()}")
    for n in SIZES:
        if n in (0, 1, 3, 7, 100, 1000):
            ps = ",".join(p.hex() for p in peaks(leaves[:n])) or "-"
            lines.append(f"peaks {n} {ps}")
        lines.append(f"root {n} {root(leaves[:n]).hex()}")
    return "\n".join(lines) + "\n"


def empty_px_root():
    """`empty.32` of the Poseidon2 vectors, in the header encoding (eight
    little-endian 32-bit words; the vector file prints each word big-endian)."""
    with open(HK) as f:
        for line in f:
            if line.startswith("empty.32 = "):
                w = line.split(" = ")[1].strip()
                return b"".join(int(w[i:i + 8], 16).to_bytes(4, "little") for i in range(0, 64, 8))
    raise SystemExit("empty.32 not found in " + HK)


def header(version, height, prev, timestamp, difficulty, tx_root, output_count, output_root,
           px_root, nonce):
    b = (struct.pack("<I", version) + le64(height) + prev + le64(timestamp) + le64(difficulty)
         + tx_root + le64(output_count) + output_root + px_root + le64(nonce))
    assert len(b) == 172
    return b


def block_id(network_id, hdr):
    return hashlib.blake2b(b"BlackSilk/block-id" + struct.pack("<I", network_id) + hdr,
                           digest_size=32).digest()


def header_values():
    lines = []
    sample = header(1, 42, bytes([7]) * 32, 1_800_000_000, 12_345, bytes([9]) * 32, 77,
                    bytes([10]) * 32, bytes([11]) * 32, 0xDEADBEEF)
    lines.append("sample header: " + sample.hex())
    lines.append("sample id (0x00DEB06E): " + block_id(0x00DEB06E, sample).hex())
    lines.append("sample id (0x0001D673): " + block_id(0x0001D673, sample).hex())
    # The mining blob (docs/consensus.md section 3): "BSilk/1" || mining_hash ||
    # LE64 nonce, mining_hash = H32("mining-hash", LE32 network_id || header[0..164]).
    for nid in (0x00DEB06E, 0xFFFFFF00):
        mh = h32("mining-hash", struct.pack("<I", nid), sample[:164])
        blob = b"BSilk/1" + mh + sample[164:]
        assert len(blob) == 47
        lines.append(f"sample pow_blob ({nid:#010x}): " + blob.hex())
    epx = empty_px_root()
    lines.append("empty PX root (header encoding): " + epx.hex())
    # Genesis (docs/consensus.md section 1): version 1, height 0, zero parent and
    # tx_root, no outputs, the empty PX root, nonce 0 (no beacon yet).
    for name, nid, t_g, d0 in [
        ("testnet", 0x0001D673, 1_790_380_800, 100),
        ("regtest", 0x00DEB06E, 1_700_000_000, 1),
        ("mainnet", 0x000B1A6C, 1_830_297_600, 100_000),
    ]:
        g = header(1, 0, bytes(32), t_g, d0, bytes(32), 0, bytes(32), epx, 0)
        lines.append(f"genesis id {name}: " + block_id(nid, g).hex())
    # The known answer of tools/genesis: the test-vector id 0xFFFFFF00, T_g
    # 1 790 000 000, D0 100, the nonce derived from Bitcoin block 0 (pinned
    # there, 0x220a72270a818150).
    g = header(1, 0, bytes(32), 1_790_000_000, 100, bytes(32), 0, bytes(32), epx,
               0x220A72270A818150)
    lines.append("genesis id tools/genesis KAT: " + block_id(0xFFFFFF00, g).hex())
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    text = table()
    # Spot checks of the definition: the empty root, and a single leaf's root.
    assert root([]) == bytes(32)
    one = leaf(*vector_output(0))
    assert root([one]) == h32("output-mmr/root", le64(1), one)
    if args.write:
        os.makedirs(os.path.dirname(DATA), exist_ok=True)
        with open(DATA, "w", newline="\n") as f:
            f.write(text)
        print(f"wrote {DATA}")
        sys.stdout.write(header_values())
    elif args.check:
        with open(DATA, newline="") as f:
            # A CRLF checkout (core.autocrlf) compares equal.
            if f.read().replace("\r\n", "\n") != text:
                print(f"{DATA} differs from the generated vectors", file=sys.stderr)
                sys.exit(1)
        print("ok")
    else:
        sys.stdout.write(text)
        sys.stdout.write(header_values())


if __name__ == "__main__":
    main()
