#!/usr/bin/env python3
"""Independent known-answer vectors for PX `Hk`, the tree node and the tree.

TEST TOOLING ONLY, NOT CORE. Nothing in the node, wallet or kernel runs this
file. It produces `px/tests/data/hk_vectors.txt`, which `px/tests/hk_vectors.rs`
checks against the Rust implementation (px-core `Hk` over the Plonky3
permutation).

Independence (what this script shares with the Rust code, and what it does not):
- It shares the Poseidon2 *instance*: BabyBear p = 2^31 - 2^27 + 1, width 16,
  S-box x^7, 8 full rounds (4 + 4) and 13 partial rounds, and the round
  constants and internal diagonal. These are transcribed below from the Plonky3
  0.7.0 registry source (`p3-baby-bear-0.7.0/src/poseidon2.rs`), which states
  they were generated by the Poseidon2 authors' Grain LFSR script
  (`generate_constants.py --field babybear --width 16`). `--registry DIR` re-reads
  that file and checks the transcription.
- It does NOT share code: the permutation is written here from the Poseidon2
  paper's definition (ePrint 2023/323: external matrix circ(2*M4, M4, M4, M4)
  with M4 = [[2,3,1,1],[1,2,3,1],[1,1,2,3],[3,1,1,2]], one external matrix
  application before the first round, internal matrix 1 + diag(V)) as plain
  matrix-vector products over Python integers. It is checked against Plonky3's
  own width-16 test vector (`test_default_babybear_poseidon2_width_16`).
- The sponge, the node, the tree and the record formulas are written from
  docs/px.md §2-§3 and docs/zk.md §4, not from px-core. The tree root is
  computed from full levels, not with a frontier.

Usage:
  python tools/vectors/poseidon2_hk.py                 # print the vector file
  python tools/vectors/poseidon2_hk.py --write         # rewrite px/tests/data/hk_vectors.txt
  python tools/vectors/poseidon2_hk.py --check         # compare with the committed file
  python tools/vectors/poseidon2_hk.py --registry ~/.cargo/registry/src/index.crates.io-*/p3-baby-bear-0.7.0

Python standard library only.
"""

import argparse
import os
import re
import sys

P = 0x7800_0001  # BabyBear: 2^31 - 2^27 + 1
WIDTH = 16
ALPHA = 7

# --- Instance constants (Plonky3 0.7.0, p3-baby-bear/src/poseidon2.rs) -------

RC_EXTERNAL_INITIAL = [
    [0x69cbb6af, 0x46ad93f9, 0x60a00f4e, 0x6b1297cd, 0x23189afe, 0x732e7bef, 0x72c246de, 0x2c941900,
     0x0557eede, 0x1580496f, 0x3a3ea77b, 0x54f3f271, 0x0f49b029, 0x47872fe1, 0x221e2e36, 0x1ab7202e],
    [0x487779a6, 0x3851c9d8, 0x38dc17c0, 0x209f8849, 0x268dcee8, 0x350c48da, 0x5b9ad32e, 0x0523272b,
     0x3f89055b, 0x01e894b2, 0x13ddedde, 0x1b2ef334, 0x7507d8b4, 0x6ceeb94e, 0x52eb6ba2, 0x50642905],
    [0x05453f3f, 0x06349efc, 0x6922787c, 0x04bfff9c, 0x768c714a, 0x3e9ff21a, 0x15737c9c, 0x2229c807,
     0x0d47f88c, 0x097e0ecc, 0x27eadba0, 0x2d7d29e4, 0x3502aaa0, 0x0f475fd7, 0x29fbda49, 0x018afffd],
    [0x0315b618, 0x6d4497d1, 0x1b171d9e, 0x52861abd, 0x2e5d0501, 0x3ec8646c, 0x6e5f250a, 0x148ae8e6,
     0x17f5fa4a, 0x3e66d284, 0x0051aa3b, 0x483f7913, 0x2cfe5f15, 0x023427ca, 0x2cc78315, 0x1e36ea47],
]
RC_EXTERNAL_FINAL = [
    [0x7290a80d, 0x6f7e5329, 0x598ec8a8, 0x76a859a0, 0x6559e868, 0x657b83af, 0x13271d3f, 0x1f876063,
     0x0aeeae37, 0x706e9ca6, 0x46400cee, 0x72a05c26, 0x2c589c9e, 0x20bd37a7, 0x6a2d3d10, 0x20523767],
    [0x5b8fe9c4, 0x2aa501d6, 0x1e01ac3e, 0x1448bc54, 0x5ce5ad1c, 0x4918a14d, 0x2c46a83f, 0x4fcf6876,
     0x61d8d5c8, 0x6ddf4ff9, 0x11fda4d3, 0x02933a8f, 0x170eaf81, 0x5a9c314f, 0x49a12590, 0x35ec52a1],
    [0x58eb1611, 0x5e481e65, 0x367125c9, 0x0eba33ba, 0x1fc28ded, 0x066399ad, 0x0cbec0ea, 0x75fd1af0,
     0x50f5bf4e, 0x643d5f41, 0x6f4fe718, 0x5b3cbbde, 0x1e3afb3e, 0x296fb027, 0x45e1547b, 0x4a8db2ab],
    [0x59986d19, 0x30bcdfa3, 0x1db63932, 0x1d7c2824, 0x53b33681, 0x0673b747, 0x038a98a3, 0x2c5bce60,
     0x351979cd, 0x5008fb73, 0x547bca78, 0x711af481, 0x3f93bf64, 0x644d987b, 0x3c8bcd87, 0x608758b8],
]
RC_INTERNAL = [
    0x5a8053c0, 0x693be639, 0x3858867d, 0x19334f6b, 0x128f0fd8, 0x4e2b1ccb, 0x61210ce0, 0x3c318939,
    0x0b5b2f22, 0x2edb11d5, 0x213effdf, 0x0cac4606, 0x241af16d,
]


def inv(x):
    return pow(x, P - 2, P)


# Internal diagonal V (the internal matrix is 1 + diag(V)), from the doc comment
# and `internal_layer_mat_mul` of p3-baby-bear 0.7.0:
# [-2, 1, 2, 1/2, 3, 4, -1/2, -3, -4, 1/2^8, 1/4, 1/8, 1/2^27, -1/2^8, -1/16, -1/2^27]
DIAG = [x % P for x in [
    -2, 1, 2, inv(2), 3, 4, -inv(2), -3, -4, inv(2 ** 8), inv(4), inv(8), inv(2 ** 27),
    -inv(2 ** 8), -inv(16), -inv(2 ** 27),
]]

M4 = [[2, 3, 1, 1], [1, 2, 3, 1], [1, 1, 2, 3], [3, 1, 1, 2]]

# The external 16x16 matrix: block (i, j) is 2*M4 on the diagonal, M4 elsewhere.
M_EXT = [[(2 if r // 4 == c // 4 else 1) * M4[r % 4][c % 4] for c in range(WIDTH)] for r in range(WIDTH)]
# The internal matrix: all ones plus diag(V).
M_INT = [[(1 + (DIAG[r] if r == c else 0)) % P for c in range(WIDTH)] for r in range(WIDTH)]


def matvec(m, v):
    return [sum(m[r][c] * v[c] for c in range(WIDTH)) % P for r in range(WIDTH)]


def permute(state):
    """Poseidon2 (ePrint 2023/323, §5) over BabyBear, t = 16."""
    assert len(state) == WIDTH and all(0 <= x < P for x in state)
    s = matvec(M_EXT, state)
    for rc in RC_EXTERNAL_INITIAL:
        s = matvec(M_EXT, [pow((x + c) % P, ALPHA, P) for x, c in zip(s, rc)])
    for c in RC_INTERNAL:
        s[0] = pow((s[0] + c) % P, ALPHA, P)
        s = matvec(M_INT, s)
    for rc in RC_EXTERNAL_FINAL:
        s = matvec(M_EXT, [pow((x + c) % P, ALPHA, P) for x, c in zip(s, rc)])
    return s


# Plonky3's width-16 known answer (p3-baby-bear 0.7.0, test_default_babybear_poseidon2_width_16).
P3_KAT_IN = [894848333, 1437655012, 1200606629, 1690012884, 71131202, 1749206695, 1717947831,
             120589055, 19776022, 42382981, 1831865506, 724844064, 171220207, 1299207443, 227047920,
             1783754913]
P3_KAT_OUT = [516096821, 90309867, 1101817252, 1660784290, 360715097, 1789519026, 1788910906,
              563338433, 319524748, 1741414159, 1650859320, 894311162, 1121347488, 1692793758,
              1052633829, 1344246938]


# --- Hk, node, tree (docs/px.md §2) ------------------------------------------

DOMAINS = {  # docs/px.md §2: 0x505800 + 1..10, in this order
    "SK": 0x505801, "NK": 0x505802, "AK": 0x505803, "OWNER": 0x505804, "DIVERSIFIER": 0x505805,
    "RECORD": 0x505806, "NULLIFIER": 0x505807, "RHO": 0x505808, "IO": 0x505809,
    "NULLIFIER_CONTRACT": 0x50580A,
}
# The reference vault's application domains (docs/contracts.md §8): the claim
# lock, the refund lock and the terms a vault record's data commits to.
LOCK_DOMAIN = 0x5641_0001
REFUND_DOMAIN = 0x5641_0002
TERMS_DOMAIN = 0x5641_0003
DEPTH = 32


def hk(domain, xs):
    """Rate 8, capacity 8 initialised to [domain, len, 0...]; add 8 elements per
    permutation into the rate; the digest is the rate after the last permutation
    (a permutation follows every full block; a trailing partial block, or an empty
    input, gets one more)."""
    assert all(0 <= x < P for x in xs)
    s = [0] * 8 + [domain, len(xs)] + [0] * 6
    blocks = [xs[i:i + 8] for i in range(0, len(xs), 8)] or [[]]
    for b in blocks:
        for i, x in enumerate(b):
            s[i] = (s[i] + x) % P
        s = permute(s)
    return s[:8]


def node(left, right):
    return permute(list(left) + list(right))[:8]


ZERO = [0] * 8


def empty_roots():
    e = [ZERO]
    for _ in range(DEPTH):
        e.append(node(e[-1], e[-1]))
    return e


def tree_root(leaves, empty):
    """Root of the depth-32 tree whose first leaves are `leaves`, the rest empty,
    computed level by level over the non-empty prefix."""
    level = [list(x) for x in leaves]
    for h in range(DEPTH):
        if not level:
            level = []
            continue
        if len(level) % 2:
            level.append(empty[h])
        level = [node(level[i], level[i + 1]) for i in range(0, len(level), 2)]
    return level[0] if level else empty[DEPTH]


def limbs16(v, n):
    return [(v >> (16 * i)) & 0xFFFF for i in range(n)]


# --- Deterministic inputs ------------------------------------------------------

def seq(n, seed):
    """n canonical elements: (seed * 1000003 + k * 0x9E3779B1) mod p."""
    return [(seed * 1000003 + k * 0x9E3779B1) % P for k in range(n)]


def leaf(i):
    return seq(8, 0x1000 + i)


LENGTHS = [0, 1, 7, 8, 9, 24, 52, 92]
TREE_SIZES = [1, 2, 3, 4, 5, 7, 8, 9, 15, 16, 17, 31, 32, 33, 63, 64, 65, 127, 128, 129, 255, 256, 257, 300]


def hexd(d):
    """A digest (or state) as big-endian 8-hex-digit words, concatenated."""
    return "".join("%08x" % x for x in d)


def vectors():
    out = []
    assert permute(P3_KAT_IN) == P3_KAT_OUT, "the permutation disagrees with Plonky3's KAT"
    out.append(("perm.p3_kat", hexd(permute(P3_KAT_IN))))
    out.append(("perm.iota", hexd(permute(list(range(16))))))
    out.append(("perm.zero", hexd(permute([0] * 16))))

    for name, dom in DOMAINS.items():
        for n in LENGTHS:
            out.append(("hk.%s.%d" % (name, n), hexd(hk(dom, seq(n, dom + n)))))
    out.append(("hk.LOCK.8", hexd(hk(LOCK_DOMAIN, seq(8, 7)))))

    out.append(("node.zero", hexd(node(ZERO, ZERO))))
    out.append(("node.ab", hexd(node(seq(8, 1), seq(8, 2)))))
    out.append(("node.ba", hexd(node(seq(8, 2), seq(8, 1)))))

    empty = empty_roots()
    for h, e in enumerate(empty):
        out.append(("empty.%d" % h, hexd(e)))
    out.append(("genesis_px_root", hexd(tree_root([], empty))))

    leaves = [leaf(i) for i in range(max(TREE_SIZES))]
    for n in TREE_SIZES:
        out.append(("frontier.%d" % n, hexd(tree_root(leaves[:n], empty))))

    # Keys, owner, record, nullifiers, rho (docs/px.md §3, zk.md §4.2-§4.4).
    sk = seq(8, 11)
    nk = hk(DOMAINS["NK"], sk)
    ak = hk(DOMAINS["AK"], sk)
    index = 0x0001_2345  # above 2^16: both halves nonzero
    d = hk(DOMAINS["DIVERSIFIER"], sk + [index & 0xFFFF, index >> 16])
    owner = hk(DOMAINS["OWNER"], ak + nk + d)
    out += [("key.nk", hexd(nk)), ("key.ak", hexd(ak)), ("key.diversifier", hexd(d)),
            ("key.owner", hexd(owner))]

    contract, asset = seq(8, 21), seq(8, 22)
    value = 0x0123_4567_89AB_CDEF
    data, rho, rcm = seq(8, 23), seq(8, 24), seq(8, 25)
    cm = hk(DOMAINS["RECORD"], owner + contract + asset + limbs16(value, 4) + data + rho + rcm)
    cm_plain = hk(DOMAINS["RECORD"], owner + ZERO + ZERO + limbs16(value, 4) + data + rho + rcm)
    nf = hk(DOMAINS["NULLIFIER"], nk + rho + cm)
    cnf = hk(DOMAINS["NULLIFIER_CONTRACT"], contract + rcm + cm)
    out += [("record.commit", hexd(cm)), ("record.commit_plain", hexd(cm_plain)),
            ("record.nullifier", hexd(nf)), ("record.contract_nullifier", hexd(cnf))]
    for j in (0, 1):
        out.append(("record.rho.%d" % j, hexd(hk(DOMAINS["RHO"], nf + [j]))))

    # io_hash (px-core call.rs doc, docs/px.md §7.2), N_IN = N_OUT = 2:
    # C ‖ per input [a, a·cm] ‖ per output [s, s·(owner ‖ contract ‖ value16[4] ‖ data)] ‖ blind
    approve = [cm, None]
    spec = [None, (owner, contract, 5000, seq(8, 26))]
    blind = seq(8, 27)
    io = list(contract)
    for a in approve:
        io += [1] + a if a is not None else [0] + ZERO
    for o in spec:
        if o is None:
            io += [0] + ZERO + ZERO + [0] * 4 + ZERO
        else:
            io += [1] + o[0] + o[1] + limbs16(o[2], 4) + o[3]
    io += blind
    assert len(io) == 92
    out.append(("call.io_hash", hexd(hk(DOMAINS["IO"], io))))

    # The vault (px/src/vault.rs; testnet v3, W28-4): both locks bind the
    # contract id; the record data is Hk(TERMS, C ‖ claim_lock ‖ refund_lock ‖
    # timeout16[4]).
    lock = hk(LOCK_DOMAIN, contract + seq(8, 31))
    refund = hk(REFUND_DOMAIN, contract + seq(8, 32))
    timeout = 0x0001_0002_0003_0004
    out.append(("vault.lock_of", hexd(lock)))
    out.append(("vault.refund_lock_of", hexd(refund)))
    out.append(("vault.terms", hexd(hk(TERMS_DOMAIN, contract + lock + refund + limbs16(timeout, 4)))))
    return out


HEADER = """\
# PX Hk / node / tree known-answer vectors.
# Generated by tools/vectors/poseidon2_hk.py (independent Python implementation;
# see its docstring for provenance). Checked by px/tests/hk_vectors.rs.
# Format: name = digest, each field element as 8 big-endian hex digits.
# Inputs: seq(n, seed)[k] = (seed * 1000003 + k * 0x9E3779B1) mod p.
"""


def render():
    return HEADER + "".join("%s = %s\n" % kv for kv in vectors())


def check_registry(root):
    path = os.path.join(os.path.expanduser(root), "src", "poseidon2.rs")
    src = open(path, encoding="utf-8").read()

    def block(name):
        m = re.search(r"pub const %s:[^=]*=(.*?)\);" % name, src, re.S)
        return [int(x, 16) for x in re.findall(r"0x[0-9a-fA-F]+", m.group(1))]

    flat = lambda rows: [x for r in rows for x in r]
    assert block("BABYBEAR_POSEIDON2_RC_16_EXTERNAL_INITIAL") == flat(RC_EXTERNAL_INITIAL)
    assert block("BABYBEAR_POSEIDON2_RC_16_EXTERNAL_FINAL") == flat(RC_EXTERNAL_FINAL)
    assert block("BABYBEAR_POSEIDON2_RC_16_INTERNAL") == RC_INTERNAL
    print("constants match %s" % path, file=sys.stderr)


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    target = os.path.join(here, "..", "..", "px", "tests", "data", "hk_vectors.txt")
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--registry", help="p3-baby-bear-0.7.0 source directory")
    args = ap.parse_args()
    if args.registry:
        check_registry(args.registry)
    text = render()
    if args.write:
        with open(target, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
    elif args.check:
        with open(target, encoding="utf-8") as f:
            if f.read().replace("\r\n", "\n") != text:
                sys.exit("MISMATCH: %s differs from this script's output" % target)
        print("ok: %s matches" % target)
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
