name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y pkg-config libssl-dev
      - name: Build
        run: cargo build --all --release
      - name: Format
        run: cargo fmt --all -- --check
      - name: Lint
        run: cargo clippy --all -- -D warnings
      - name: Test
        run: cargo test --all --features fuzzing -- --nocapture
      - name: Audit
        run: cargo audit || true
