//! Consensus pins on third-party cryptography (docs/reviews/dependency-review.md).
//! Every PX commitment, nullifier, tree node, program id and Fiat–Shamir
//! challenge depends on this exact permutation. A dependency upgrade that
//! changed it would silently fork the chain; this test makes it fail loudly.

use blacksilk_zk::config::{permutation, Val};
use p3_field::PrimeField32;
use p3_symmetric::Permutation;

/// Poseidon2, BabyBear, width 16, Plonky3's default constants (generated by
/// the Poseidon2 authors' `generate_constants.py`). The vector is the one in
/// `p3-baby-bear` 0.7.0 (`test_default_babybear_poseidon2_width_16`).
#[test]
fn poseidon2_is_the_pinned_permutation() {
    let input: [u32; 16] = [
        894848333, 1437655012, 1200606629, 1690012884, 71131202, 1749206695, 1717947831, 120589055,
        19776022, 42382981, 1831865506, 724844064, 171220207, 1299207443, 227047920, 1783754913,
    ];
    let expected: [u32; 16] = [
        516096821, 90309867, 1101817252, 1660784290, 360715097, 1789519026, 1788910906, 563338433,
        319524748, 1741414159, 1650859320, 894311162, 1121347488, 1692793758, 1052633829,
        1344246938,
    ];
    let mut state = input.map(Val::new);
    permutation().permute_mut(&mut state);
    assert_eq!(state.map(|x| x.as_canonical_u32()), expected);
}
